pipeline {
    agent any

    options {
        ansiColor('xterm')
    }

    environment {
        DAGGER_NO_NAG = 1
        DAGGER_VERSION = "0.18.3"
        PATH = "/tmp/dagger/bin:$PATH"
        _EXPERIMENTAL_DAGGER_RUNNER_HOST = "tcp://dagger:1234"
    }

    stages {
        stage("dagger") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'nexus-credentials', passwordVariable: 'NEXUS_PASSWORD', usernameVariable: 'NEXUS_USER')]) {
                    sh '''
                        curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=/tmp/dagger/bin DAGGER_VERSION=$DAGGER_VERSION sh
                        rm -rf dagger-modules && git clone http://gitea:3000/admin/dagger-modules/ dagger-modules
                        dagger call -m ./dagger-modules/java/java-build publish \
                        --source=./ \
                        --username $NEXUS_USER \
                        --password env:NEXUS_PASSWORD \
                        --artifactRepository "nexus.local" \
                        --artifactId "hello-world" \
                        --artifactVersion 1.0.0 \
                        --imageRepository "nexus.local" \
                        --imageName "docker-repo/hello-world" \
                        --imageVersion 1.0.0
                    '''
                }
            }
        }
    }
}