services:

  jaeger:
    hostname: jaeger
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "14268:14268"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  nginx:
    hostname: nginx
    container_name: nginx
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8081:80

  nexus:
    hostname: nexus
    container_name: nexus
    image: sonatype/nexus3
    restart: always
    volumes:
      - ./nexus/data:/data
    # ports:
      # - 8081:8081
      # - 5000:5000

  gitea:
    hostname: gitea
    container_name: gitea
    image: docker.gitea.com/gitea:1.23.6
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    ports:
      - "3000:3000"
      - "222:22"
    volumes:
      - ./gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  jenkins:
    hostname: jenkins
    container_name: jenkins
    image: jenkins-image
    build:
      context: ./jenkins
      dockerfile: Dockerfile
      args:
        GITEA_USER: ${GITEA_USER}
        GITEA_PASSWORD: ${GITEA_PASSWORD}
        NEXUS_USER: ${NEXUS_USER}
        NEXUS_PASSWORD: ${NEXUS_PASSWORD}
        JENKINS_ADMIN_USER: ${JENKINS_ADMIN_USER}
        JENKINS_ADMIN_PASSWORD: ${JENKINS_ADMIN_PASSWORD}
        JENKINS_FOLDER: ${JENKINS_FOLDER}
    group_add:
        - 999
    privileged: true
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker