services:

  dagger:
    hostname: dagger
    container_name: dagger
    image: dagger-image
    build:
      context: ./dagger
      dockerfile: Dockerfile
    restart: always
    privileged: true
    ports:
      - "1234:1234"
    links:
      - "nginx:nexus.local"
    volumes:
      - dagger-engine:/var/lib/dagger

  jaeger:
    hostname: jaeger
    container_name: jaeger
    image: jaegertracing/jaeger:2.5.0
    restart: always
    ports:
      - "14268:14268"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  nginx:
    hostname: nginx
    container_name: nginx
    image: nginx-image
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"

  nexus:
    hostname: nexus
    container_name: nexus
    image: sonatype/nexus3:3.59.0
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - nexus:/nexus-data

  gitea:
    hostname: gitea
    container_name: gitea
    image: gitea-image
    build:
      context: ./gitea
      dockerfile: Dockerfile
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    ports:
      - "3000:3000"
      - "222:22"
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  jenkins:
    hostname: jenkins
    container_name: jenkins
    image: jenkins-image
    build:
      context: ./jenkins
      dockerfile: Dockerfile
      args:
        GITEA_USER: ${GITEA_USER}
        GITEA_PASSWORD: ${GITEA_PASSWORD}
        NEXUS_USER: ${NEXUS_USER}
        NEXUS_PASSWORD: ${NEXUS_PASSWORD}
        JENKINS_USER: ${JENKINS_USER}
        JENKINS_PASSWORD: ${JENKINS_PASSWORD}
    privileged: true
    ports:
      - "8090:8080"
      - "50000:50000"
    links:
      - "nginx:nexus.local"
    volumes:
      - jenkins:/var/jenkins_home

volumes:
  dagger-engine:
  nexus:
  jenkins:
  gitea:
